### ISSUE TITLE
Forwards and Backwards not working properly

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/DroidControlShip#10]
Motor speed setpoints for full forward and full backwards are not correctly reproduced by the target. Target drives in a circle instead of straight.
Problem may be on the setpoints or in the differential drive of RadonUlzer

**Comment by gabryelreyes** [comment]
Magic number is 32600 for motor linear speed setpoint. This is the max. speed that can be set through the differencial drive without it driving in circles. The problem is found on the left motors specially.

**Comment by BlueAndi** [comment]
I don't get it completly. Can you point out where this magic number can be found?

**Comment by gabryelreyes** [comment]
It is the motor speed setpoint sent through MQTT and then SMP to RU. It is correctly received and parsed by RU.
 It is then used to call DifferentialDrive.setLinearSpeed

**Comment by gabryelreyes** [comment]
Basically, this works as intended:
```cpp
DifferentialDrive::getInstance().setLinearSpeed(32600 , 32600);
```
while this makes the robot drive in circles:
```cpp 
/* INT16_MAX = 32767 */
DifferentialDrive::getInstance().setLinearSpeed(INT16_MAX , INT16_MAX);
```

**Comment by gabryelreyes** [comment]
Fixed in https://github.com/BlueAndi/RadonUlzer/commit/0d7cd96148713fa04e0cc1e65c54f0779aedd3b7
