### ISSUE TITLE
Simplify INetwork configuration

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/DroidControlShip#13]
Configuration parameters are set as function arguments in setConfig().
Better approach would be to use a struct.
First mentioned [here](https://github.com/BlueAndi/DroidControlShip/pull/12#discussion_r1341247790)

**Comment by gabryelreyes** [comment]
@LuDubies maybe use implement this as part of your rework?

**Comment by LuDubies** [comment]
Settings structs for mqtt and network are present in [cf34194](https://github.com/BlueAndi/DroidControlShip/commit/cf3419458d72570285786a8b57cf3ba4f4359d7b)
