### ISSUE TITLE
Documentation Enhancement

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/DroidControlShip#18]
Following Topics should be included or enhanced in the documentation:

**Comment by LuDubies** [comment]
Current MSYS2 example uses ucrt. When following the MSYS2 installation, ucrt will be used so the respective mosquitto has to be used.
Include ```pacman -Sy mingw-w64-ucrt-x86_64-mosquitto``` in the documentation instead of ```pacman -Sy mingw-w64-x86_64-mosquitto```

**Comment by LuDubies** [comment]
- [ ] mention either CP2102 drivers or link to esp32 flashing documentation. Alternatively, extend documentation in [the ZumocomSystem repo](https://github.com/NewTec-GmbH/ZumoComSystem) and link to that.
