### ISSUE TITLE
Improve Network

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/DroidControlShip#50]
- Network shall print its current IP address once it is connected to a WiFi Access Point (in STA mode), or it has activated its AP Mode.
- A method is required to get the status or the current state of the network component. This is important to initialize webserver components AFTER the network stack has been initialized.

**Comment by BlueAndi** [comment]
Just an idea:

After  WiFi.mode() is set, you can call the webserver begin() method. Btw the Network is calling getMode() before mode() which returns WIFI_MODE_NULL, be aware of this!

The app should just ask network.isUp() ... any if yes ... do.

isUp() means Wifi.mode() was set ... which means whether the "interface" is up and not the link.

isConnected() would mean the link is up in case of station mode.
