### ISSUE TITLE
Network: IPAddress

### ISSUE THREAD

**Issue by gabryelreyes** [BlueAndi/DroidControlShip#54]
`getIP` method shall return an IPAddress instead of a String. This allows the application to better decide what to do with the information.

**Comment by gabryelreyes** [comment]
@nhjschulz Could you please fix this issue in `Network` , now that you implemented IPAddress?
https://github.com/BlueAndi/DroidControlShip/blob/17e7f4adf03700e9bc9b47afbc158b3c47bf8eb3/lib/HALInterfaces/src/INetwork.h#L111

**Comment by nhjschulz** [comment]
Fixed with PR #155
